# Generated by Django 6.0 on 2026-01-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_create',
            new_name='dateCreate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_update',
            new_name='dateUpdate',
        ),
    ]
