# Generated by Django 6.0 on 2026-01-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_date_create_post_datecreate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datePublish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
