# Generated by Django 6.0 on 2026-01-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_datepublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
